[package]
name = "rust-cc"
description = "A cycle collector for Rust programs"
version.workspace = true
authors.workspace = true
readme = "README.md"
repository.workspace = true
categories.workspace = true
keywords = ["cycle", "cycles", "collector", "garbage", "memory"]
license.workspace = true
edition.workspace = true

[workspace]
members = ["derive"]

[workspace.package]
version = "0.1.0"
authors = ["fren_gor <goro@frengor.com>"]
repository = "https://github.com/frengor/rust-cc"
categories = ["memory-management"]
license = "MIT OR Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["auto-collect"]
full = ["auto-collect"]
nightly = []
auto-collect = []
pedantic-debug-assertions = []

[dependencies]
thiserror = "1.0.37"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
rand = "0.8.3"

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "shredder_benchmark"
harness = false

