[package]
name = "rust-cc"
description = "A cycle collector for Rust programs"
version = "0.1.0"
authors = ["fren_gor <goro@frengor.com>"]
readme = "README.md"
repository = "https://github.com/frengor/rust-cc"
categories = ["memory-management"]
keywords = ["garbage", "cycle", "cycles", "collector", "memory"]
license = "MIT OR Apache-2.0"
edition = "2021"

# For the moment avoid publishing the package
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default=["auto-collect"]
nightly = []
auto-collect = []

[dependencies]
thiserror = "1.0.37"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
rand = "0.8.3"

[[bench]]
name = "bench"
harness = false

[[bench]]
name = "shredder_benchmark"
harness = false

