name: Check and Clippy

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  on-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: taiki-e/install-action@cargo-hack
      - name: Check and Clippy
        # Keep "std" feature always enabled on stable to avoid needing the no-std related nightly features
        # Also don't use --workspace (but run two commands) since rust-cc-derive hasn't a "std" feature
        run: |
          cargo hack check --all-targets --feature-powerset --skip nightly --clean-per-run --verbose -F std
          cargo hack check --all-targets --feature-powerset --skip nightly --clean-per-run --verbose --manifest-path derive/Cargo.toml
          cargo hack clippy --all-targets --feature-powerset --skip nightly --clean-per-run --verbose -F std -- -D warnings
          cargo hack clippy --all-targets --feature-powerset --skip nightly --clean-per-run --verbose --manifest-path derive/Cargo.toml -- -D warnings
  on-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: taiki-e/install-action@cargo-hack
      - name: Check and Clippy (nightly)
        # No need to use --workspace here, since there's no nightly feature in rust-cc-derive
        run: |
          cargo hack check --all-targets --feature-powerset --clean-per-run --verbose -F nightly
          cargo hack clippy --all-targets --feature-powerset --clean-per-run --verbose -F nightly -- -D warnings
  docs:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build docs
        run: cargo doc --no-deps --all-features --verbose
