name: Miri

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  test-with-miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # From Miri documentation: https://github.com/rust-lang/miri#running-miri-on-ci
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - uses: taiki-e/install-action@cargo-hack
      - name: Run tests
        run: cargo hack miri test --feature-powerset --skip nightly --verbose --workspace
      - name: Run tests (nightly)
        run: cargo hack miri test --feature-powerset --verbose --workspace -F nightly
