name: Build and Test nightly

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use nightly toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          override: true
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run tests
        run: cargo test --verbose --workspace
      - name: Build with nightly feature
        run: cargo build -F nightly --verbose --workspace
      - name: Run tests with nightly feature
        run: cargo test -F nightly --verbose --workspace
      - name: Build with every feature
        run: cargo build --all-features --verbose --workspace
      - name: Run tests with every feature
        run: cargo test --all-features --verbose --workspace
