name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  on-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-hack
      - name: Run tests
        # Keep "std" feature always enabled on stable to avoid needing the no-std related nightly features
        run: |
          cargo hack test --feature-powerset --ignore-unknown-features --workspace --skip nightly --verbose -F std
  on-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-hack
      - name: Run tests
        run: cargo hack test --feature-powerset --ignore-unknown-features --workspace --verbose -F nightly
